### ISSUE TITLE
Basic Controller

### ISSUE THREAD

**Issue by SmejoTT** [automat-ed/simulation#2]
# Task

For Demo 1 create a controller for the robot that can work with ROS and does:
- [x] Velocity Control
- [x] Steering angle control 
- [x] Spotlight on/off control
- [x] ROS node in Webots Controller
