### ISSUE TITLE
Impose velocity limits for differential steering

### ISSUE THREAD

**Issue by SmejoTT** [automat-ed/simulation#35]
# Task

- [ ] Set the velocity limit on the motors based on the real hardware
- [ ] Add velocity check to the ```lib/steering/src/diffSteering.cpp``` so the velocity is under the limit
- [ ] If the limit is exceeded set the velocity to the limit
