### ISSUE TITLE
Populate environment with static obstacles

### ISSUE THREAD

**Issue by SmejoTT** [automat-ed/simulation#36]
# Task

- [ ] Make a copy of each of the basic environments
- [x] Add static obstacles on the path
- [x] Add trees along the path
